language: r
cache: packages
pandoc_version: 1.19.2.1

env:
    global: 
        - secure: mjcXqzxZJ2pAb4XgqVOV3wV58BhwhQQIRVIRzWoYbPIiy33ehEXMLwXcUXmYr47fME6MWdalPr9A424cIMS0tqA1nWKgC4NZRj975WtwUAY1ZWgU6varDmBMt+AcHceREV8+9BmA5Vo0R2tEgyzjVdCYN1Jy6uL9sqJAf8FqIN3J8HiYYDKQ+xcL5lVwnke7AwQiayt87iJeVXyLUXeXpuPYWBWzSUTNc58c7g/eKSe+nYsqHGRFgwnVpVUUIjqjpMWK3F+VWjY/DAwrVnLTQjsGZ5d9Wvdx4pWRZb28NiABHFbzbm6Hue0pHG7pTWYpwTjhv71RNqE1VUnmlAjhouyFTj1gFS+eTFeJaoqex/wBvMdmsxH0TkIi1p5nhCoMw0xwgRwnknvrDtxCBBpXNud/sTG4ESZQg1+lJ8S59A2Hc4+gott2MKarb3cb6tbpl1T5MKbOJ5HIJS2tp0C+vRqtrKvKl3vAuoKbs5gcVvvkZgtxmYKKWSGVlOT1BKrAhrohtuiglcelzvUO3YuvzzQAMMnlc7466jOB7CrKBlUMYEpxWWNSKCZaghmLi/c7YM/DsG/FPU2FbQSC9ZnbsDCYiwCfPfNmMHJBOs4d+1H8XBvlFF1JMxzJWE86uV/QlU5+o96qXhc4x6i87t8SHv19E/IedbUTqLNPeRA31Is=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
